[platformio]
default_envs = tag
core_dir = .pio-core
src_dir = hardware/platformio/src
lib_dir = hardware/platformio/lib

[env]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+

[env:tag]
build_src_filter = +<tag/> -<anchor_1782/> -<anchor_1783/> -<anchor_1784/> -<calib_anchor/>
monitor_filters = esp32_exception_decoder, time

[env:anchor_1782]
build_src_filter = +<anchor_1782/> -<tag/> -<anchor_1783/> -<anchor_1784/> -<calib_anchor/>

[env:anchor_1783]
build_src_filter = +<anchor_1783/> -<tag/> -<anchor_1782/> -<anchor_1784/> -<calib_anchor/>

[env:anchor_1784]
build_src_filter = +<anchor_1784/> -<tag/> -<anchor_1782/> -<anchor_1783/> -<calib_anchor/>

[env:calib_anchor]
build_src_filter = +<calib_anchor/> -<tag/> -<anchor_1782/> -<anchor_1783/> -<anchor_1784/>
